# Generated by Django 6.0.4 on 2026-05-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
