# Generated by Django 6.0.4 on 2026-05-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegu', '0002_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='receipe_image',
        ),
    ]
